// ============================================================================
// SewaSathi — database.types.ts
// Hand-authored to match 001_sewasathi_schema.sql.
// If you have the Supabase CLI, regenerate with:
//   supabase gen types typescript --project-id <project-ref> > database.types.ts
// ============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "citizen" | "admin" | "department_worker";
export type ReportPriority = "low" | "medium" | "high" | "emergency";
export type ReportStatus =
  | "submitted"
  | "verified"
  | "assigned"
  | "in_progress"
  | "resolved"
  | "rejected";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone_number: string | null;
          role: UserRole;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone_number?: string | null;
          role?: UserRole;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone_number?: string | null;
          role?: UserRole;
          created_at?: string;
        };
      };

      departments: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
      };

      categories: {
        Row: {
          id: string;
          name: string;
          default_department_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          default_department_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          default_department_id?: string | null;
          created_at?: string;
        };
      };

      reports: {
        Row: {
          id: string;
          tracking_id: string;
          user_id: string | null;
          category_id: string | null;
          department_id: string | null;
          priority: ReportPriority;
          status: ReportStatus;
          description: string;
          ward_number: number | null;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tracking_id?: string; // auto-generated by trigger if omitted
          user_id?: string | null;
          category_id?: string | null;
          department_id?: string | null;
          priority?: ReportPriority;
          status?: ReportStatus;
          description: string;
          ward_number?: number | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tracking_id?: string;
          user_id?: string | null;
          category_id?: string | null;
          department_id?: string | null;
          priority?: ReportPriority;
          status?: ReportStatus;
          description?: string;
          ward_number?: number | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };

      report_media: {
        Row: {
          id: string;
          report_id: string;
          media_url: string;
          media_type: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          media_url: string;
          media_type?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          report_id?: string;
          media_url?: string;
          media_type?: string;
          created_at?: string;
        };
      };

      status_logs: {
        Row: {
          id: string;
          report_id: string;
          previous_status: ReportStatus | null;
          new_status: ReportStatus;
          updated_by: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          previous_status?: ReportStatus | null;
          new_status: ReportStatus;
          updated_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          report_id?: string;
          previous_status?: ReportStatus | null;
          new_status?: ReportStatus;
          updated_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
      };
    };

    Views: Record<string, never>;

    Functions: {
      get_my_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
      update_report_status: {
        Args: {
          p_report_id: string;
          p_new_status: ReportStatus;
          p_note?: string | null;
        };
        Returns: Database["public"]["Tables"]["reports"]["Row"];
      };
    };

    Enums: {
      user_role: UserRole;
      report_priority: ReportPriority;
      report_status: ReportStatus;
    };
  };
}

// Convenience row aliases
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Department = Database["public"]["Tables"]["departments"]["Row"];
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Report = Database["public"]["Tables"]["reports"]["Row"];
export type ReportInsert = Database["public"]["Tables"]["reports"]["Insert"];
export type ReportMedia = Database["public"]["Tables"]["report_media"]["Row"];
export type StatusLog = Database["public"]["Tables"]["status_logs"]["Row"];
